### PR TITLE
added support for PHP 8.0

### PR DESCRIPTION
**Pull request by abame**
added support for PHP 8.0 in composer.json and CI, regenerated phpunit.xml for PHPUnit 9.5

referenced to issue #21

### CODE REVIEW

**Comment by abame** [comment]
is there a reason why this method `\Werkspot\Bundle\SitemapBundle\Controller\GenerateController::render` has visibility set to `protected` but php-cs-fixer complains that it should be set to `private`?

I mean, it's used only in `GenerateController` but since it's been set with visibility `protected` it might be used already from some other implementation that extends this controller.

How should this be handled then? Or we just ignore the reported issue as a false positive?

**Comment by henriquemoody** [comment]
Hey, @abame! Thanks for contributing!

I think the reason is that `GenerateController` is a final class, therefore there no point on having a `protected` method.

It would be great if you fix it!

**Comment by abame** [comment]
CI is failing for PHP 8.0 and Symfony 5 because of a deprecated PHP method in libxml. This deprecation is triggered only for a `LIBXML_VERSION` < 20900 so somehow in travis ci we need to upgrade the libxml version but I'm not sure how since I'm not really familiar with travis ci. 

Any help is appreciated :pray:

**Comment by abame** [comment]
> CI is failing for PHP 8.0 and Symfony 5 because of a deprecated PHP method in libxml. This deprecation is triggered only for a `LIBXML_VERSION` < 20900 so somehow in travis ci we need to upgrade the libxml version but I'm not sure how since I'm not really familiar with travis ci.
> 
> Any help is appreciated

@henriquemoody all green with Symfony 5.2 since there was a patch provided there for the deprecated version of libxml

**Comment by henriquemoody** [comment]
Thank you so much for contributing! I will ask someone with merge privileges to merge your pull request!

**Pull request merged**
